# Generated by Django 3.0.2 on 2020-01-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('cc_myself', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('registrationNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('password_repeat', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('verified', models.BooleanField()),
            ],
        ),
    ]
