# Generated by Django 3.0.2 on 2020-01-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
