# Generated by Django 3.0.2 on 2020-01-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField()),
                ('e_title', models.CharField(max_length=255)),
                ('e_data', models.TextField()),
            ],
        ),
    ]
